version: '3.8'

services:
  mysql:
    image: mariadb:10.6
    container_name: mariadb-socket-db
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: socketdb
      MARIADB_USER: socketuser
      MARIADB_PASSWORD: socketpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - socket-network

  app:
    build: .
    container_name: universaldb-socket-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=socketuser
      - DB_PASSWORD=socketpass
      - DB_NAME=socketdb
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - mysql
    networks:
      - socket-network
    volumes:
      - ./public:/app/public

volumes:
  mysql_data:

networks:
  socket-network:
    driver: bridge